[pytest]
addopts = -ra --strict-config --strict-markers
filterwarnings =
    ignore:Using `httpx` with `starlette\.testclient` is deprecated.*:starlette.exceptions.StarletteDeprecationWarning
testpaths = tests
